site_name: FANUC Robots Vision Manual
site_description: Example FANUC (R-30iB) integration for the wenglor robot vision API.
site_url: https://wenglor.github.io/wenglor-fanuc-robots-vision/
repo_url: https://github.com/wenglor/wenglor-fanuc-robots-vision
repo_name: wenglor-fanuc-robots-vision
use_directory_urls: true

theme:
  name: material
  logo: images/wenglor_logo.svg
  features:
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - search.highlight

nav:
  - index.md
  - 1. Installation & Setup:
    - 1_0_installation/index.md
  - 2. User Configuration:
    - 2_0_user_configuration/index.md
  - 3. Robot Program:
    - 3_0_robot_program/index.md
  - 4. KAREL Reference:
    - 4_0_reference/index.md
  - 5. Troubleshooting:
    - 5_0_troubleshooting/index.md
  - 6. Support & Feedback:
    - 6_0_support_and_feedback/index.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

docs_dir: docs

extra:
  generator: false

copyright: "© 2026 wenglor sensoric group"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/image_format.css
  - css/wenglor.css
